version: '2'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - casepro
    links:
      - casepro
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  casepro:
    image: praekeltfoundation/casepro-docker:sha-2d79e56
    ports:
      - "8000:8000"
    environment:
      - EMAIL_PORT=email_port_placeholder
      - EMAIL_HOST_USER=email_username_placeholder
      - EMAIL_HOST_PASSWORD=email_password_placeholder
      - EMAIL_HOST=email_host_placeholder
      - SITE_HOST_PATTERN=site_domain_placeholder
      - CASEPRO_DATABASE=database_host_placeholder
      - REDIS_HOST=redis_host_placeholder
      - REDIS_PORT=redis_db_placeholder
      - SECRET_KEY=secret_key_placeholder
      - HOSTNAME=site_domain_placeholder
      - SITE_API_HOST=rapidpro_url_placeholder
      - C_FORCE_ROOT=true
      - SITE_CASE_RESPONSE_REQUIRED_TIME=60
      - SITE_CONTACT_DISPLAY=name
      - SITE_EXTERNAL_CONTACT_URL=rapidpro_contact_url_placeholder
      - SITE_BACKEND=casepro.backend.rapidpro.RapidProBackend
      - MESSAGE_SYNC_INTERVAl=20
  celery:
    image: praekeltfoundation/casepro-docker:sha-2d79e56
    depends_on:
      - casepro
    environment:
      - EMAIL_PORT=email_port_placeholder
      - EMAIL_HOST_USER=email_username_placeholder
      - EMAIL_HOST_PASSWORD=email_password_placeholder
      - EMAIL_HOST=email_host_placeholder
      - SITE_HOST_PATTERN=site_domain_placeholder
      - CASEPRO_DATABASE=database_host_placeholder
      - REDIS_HOST=redis_host_placeholder
      - REDIS_PORT=redis_db_placeholder
      - SECRET_KEY=secret_key_placeholder
      - HOSTNAME=site_domain_placeholder
      - SITE_API_HOST=rapidpro_url_placeholder
      - C_FORCE_ROOT=true
      - SITE_CASE_RESPONSE_REQUIRED_TIME=60
      - SITE_CONTACT_DISPLAY=name
      - SITE_EXTERNAL_CONTACT_URL=rapidpro_contact_url_placeholder
      - SITE_BACKEND=casepro.backend.rapidpro.RapidProBackend
      - MESSAGE_SYNC_INTERVAl=20
    command: ["celery", "--beat", "--app=casepro", "worker", "--loglevel=INFO", "--queues=celery,sync", "--concurrency=1"]
