version: '2'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - casepro
    links:
      - casepro
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  casepro:
    image: praekeltfoundation/casepro-docker:v0.0.259
    depends_on:
      - redis
      - postgresql
    ports:
      - "8000:8000"
    environment:
      - EMAIL_PORT=email_port_placeholder
      - EMAIL_HOST_USER=email_username_placeholder
      - EMAIL_HOST_PASSWORD=email_password_placeholder
      - EMAIL_HOST=email_host_placeholder
      - SITE_HOST_PATTERN=site_domain_placeholder
      - CASEPRO_DATABASE=postgresql://postgres:postgres@postgresql/casepro
      - REDIS_HOST=redis:6379
      - REDIS_PORT=1
      - SECRET_KEY=super-secret-key
      - HOSTNAME=site_domain_placeholder
      - SITE_API_HOST=https://rapidpro.praekelt.org/
      - C_FORCE_ROOT=true
      - SITE_CASE_RESPONSE_REQUIRED_TIME=60
      - SITE_CONTACT_DISPLAY=name
      - SITE_EXTERNAL_CONTACT_URL=https://rapidpro.praekelt.org/contact/read/%s/
      - SITE_BACKEND=casepro.backend.rapidpro.RapidProBackend
      - MESSAGE_SYNC_INTERVAl=20
  celery:
    image: praekeltfoundation/casepro-docker:v0.0.259
    depends_on:
      - casepro
    links:
      - redis
      - postgresql
    environment:
      - EMAIL_PORT=email_port_placeholder
      - EMAIL_HOST_USER=email_username_placeholder
      - EMAIL_HOST_PASSWORD=email_password_placeholder
      - EMAIL_HOST=email_host_placeholder
      - SITE_HOST_PATTERN=site_domain_placeholder
      - CASEPRO_DATABASE=postgresql://postgres:postgres@postgresql/casepro
      - REDIS_HOST=redis:6379
      - REDIS_PORT=1
      - SECRET_KEY=super-secret-key
      - HOSTNAME=site_domain_placeholder
      - SITE_API_HOST=https://rapidpro.praekelt.org/
      - C_FORCE_ROOT=true
      - SITE_CASE_RESPONSE_REQUIRED_TIME=60
      - SITE_CONTACT_DISPLAY=name
      - SITE_EXTERNAL_CONTACT_URL=https://rapidpro.praekelt.org/contact/read/%s/
      - SITE_BACKEND=casepro.backend.rapidpro.RapidProBackend
      - MESSAGE_SYNC_INTERVAl=20
    command: ["celery", "--beat", "--app=casepro", "worker", "--loglevel=INFO", "--queues=celery,sync", "--concurrency=1"]
  redis:
    image: redis:alpine
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=casepro

volumes:
  es_data:
