version: '2'
services:
  nginx:
    image: nginx:latest
    depends_on:
      - rapidpro
    links:
      - rapidpro
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  rapidpro:
    image: praekeltfoundation/rapidpro:v3.0.334
    depends_on:
      - redis
      - postgresql
    ports:
      - 8000:8000
    environment:
      - DOMAIN_NAME=rapidpro_domain_placeholder
      - ALLOWED_HOSTS=rapidpro_domain_placeholder
      - TEMBA_HOST=rapidpro_domain_placeholder
      - DJANGO_DEBUG=off
      - DATABASE_URL=database_url_placeholder
      - REDIS_URL=redis_url_placeholder
      - SECRET_KEY=secret_key_placeholder
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=on
      - MANAGEPY_MIGRATE=on
      - SEND_AIRTIME=on
      - SEND_EMAILS=on
      - SEND_WEBHOOKS=on
      - DJANGO_COMPRESSOR=on
      - SEND_MESSAGES=on
      - SEND_CALLS=on
      - EMAIL_HOST=email_host_placeholder
      - EMAIL_HOST_USER=email_username_placeholder
      - EMAIL_HOST_PASSWORD=email_password_placeholder
      - EMAIL_PORT=email_port_placeholder
      - BRANDING_LINK=rapidpro_url_placeholder
      - CLEAR_COMPRESSOR_CACHE=on
      - DEFAULT_FROM_EMAIL=from_email_placeholder
  celery:
    image: praekeltfoundation/rapidpro:v3.0.334
    depends_on:
      - rapidpro
    links:
      - redis
      - postgresql
    environment:
      - DOMAIN_NAME=rapidpro_domain_placeholder
      - ALLOWED_HOSTS=rapidpro_domain_placeholder
      - TEMBA_HOST=rapidpro_domain_placeholder
      - DJANGO_DEBUG=off
      - DATABASE_URL=database_url_placeholder
      - REDIS_URL=redis_url_placeholder
      - SECRET_KEY=secret_key_placeholder
      - MANAGEPY_COLLECTSTATIC=on
      - MANAGEPY_COMPRESS=on
      - MANAGEPY_INIT_DB=on
      - MANAGEPY_MIGRATE=on
      - SEND_AIRTIME=on
      - SEND_EMAILS=on
      - SEND_WEBHOOKS=on
      - DJANGO_COMPRESSOR=on
      - SEND_MESSAGES=on
      - SEND_CALLS=on
      - EMAIL_HOST=email_host_placeholder
      - EMAIL_HOST_USER=email_username_placeholder
      - EMAIL_HOST_PASSWORD=email_password_placeholder
      - EMAIL_PORT=email_port_placeholder
      - BRANDING_LINK=rapidpro_url_placeholder
      - CLEAR_COMPRESSOR_CACHE=on
      - DEFAULT_FROM_EMAIL=from_email_placeholder
    command: ["/venv/bin/celery", "--beat", "--app=temba", "worker", "--loglevel=INFO", "--queues=celery,batch"]
  redis:
    image: redis:alpine
  postgresql:
    image: mdillon/postgis:9.6
    environment:
      - POSTGRES_DB=rapidpro

volumes:
  es_data: